services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ./client
    command: npm run start
    ports:
      - 8080:8000
    volumes:
      - ./client/src/:/app/src/
      - ./client/public/:/app/public/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
